name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
#   test:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#           os: [macos-latest, windows-latest, ubuntu-latest]
#           python-version: [3.7, 3.8]
#     steps:
#     - uses: actions/checkout@v2
#     - name: Run tests
#       run: cargo test --verbose
      
  maturin_build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [macos-latest, windows-latest, ubuntu-latest]
          python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install maturin        
        run: |
          pip install maturin
          pip install virtualenv
          virtualenv sc2_helper_env
          
      - if: matrix.os == 'windows-latest'
        run: |
          "sc2_helper_env/Scripts/activate"
      - if: matrix.os == 'macos-latest'
        run: |
          source sc2_helper_env/bin/activate
      - if: matrix.os == 'ubuntu-latest'
        run: |
          source sc2_helper_env/bin/activate
      - name: Build package
        run: |
          maturin develop --release
  
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [macos-latest, windows-latest, ubuntu-latest]
          python-version: [3.7, 3.8]
    needs: [maturin_build]
    steps:
    - uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: sc2_helper/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
